build_from:
  amd64: ghcr.io/home-assistant/amd64-addon-base:17.2.0
  aarch64: ghcr.io/home-assistant/aarch64-addon-base:17.2.0
  armv7: ghcr.io/home-assistant/armv7-addon-base:17.2.0
  armhf: ghcr.io/home-assistant/armhf-addon-base:17.2.0
  i386: ghcr.io/home-assistant/i386-addon-base:17.2.0
args:
  PYTHON_VERSION: "3.12"
